### ISSUE TITLE
Default origin on localhost

### ISSUE THREAD

**Issue by juliancwirko** [ElrondNetwork/native-auth-client#18]
When the `origin` is not set in `new NativeAuthClient(...)` and I test locally, using it with, for example: `http://localhost:3000`, I always get blocked by the xPortal phishing 'gatekeeper'. When I pass `http://localhost:3000` as `origin` to `NativeAuthClient` initialization, then it's ok. This is because the default `window.loaction.hostname` won't include the port.

I wonder what is the reason to use `hostname` instead of `origin` or `host` here: https://github.com/multiversx/mx-sdk-js-native-auth-client/blob/main/src/entities/native.auth.client.config.ts#L2 ? 

I am sure that it worked previously, or at least xPortal didn't block it in such a case for localhost. So there could be two solutions. On the xPortal side, let it work on localhost without the gatekeeper or if this won't break anything, we could use `window.location.origin` or `window.location.host` here.

xPortal for Android 2.0.39
all JS SKDs up to date

**Comment by tanghel** [comment]
Thank you for the feedback!
Indeed, when first implementing this, we did not include the protocol, which was an added functionality later on.

The following PR: https://github.com/multiversx/mx-sdk-js-native-auth-client/pull/19
should fix this
